development:
  adapter: postgresql
  database: bootstrap_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: bootstrap_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bootstrap_production
  pool: 5
  timeout: 5000
