development:
  adapter: postgresql
  database: sistemico_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: sistemico_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sistemico_production
  pool: 5
  timeout: 5000
